from __future__ import annotations

METHOD_CATALOG = {
    "Time series": {
        "Preliminary analysis and transformations": [
            "Time plots and seasonal plots",
            "Rolling mean, variance, covariance and correlation",
            "Lag plots",
            "Autocorrelation function",
            "Partial autocorrelation function",
            "Cross-correlation functions",
            "Differencing and seasonal differencing",
            "Logarithmic, Box-Cox and Yeo-Johnson transformations",
            "Linear and polynomial detrending",
            "Classical seasonal decomposition",
            "STL decomposition",
            "MSTL multiple-seasonal decomposition",
            "Hodrick-Prescott filter",
            "Baxter-King filter",
            "Christiano-Fitzgerald filter",
            "Moving-average smoothing",
            "Exponential smoothing",
            "Fourier and spectral decomposition",
        ],
        "Stationarity and unit roots": [
            "Augmented Dickey-Fuller",
            "Dickey-Fuller GLS",
            "Phillips-Perron",
            "KPSS",
            "Zivot-Andrews",
            "Variance-ratio test",
            "Seasonal unit-root procedures",
            "Multiple-break unit-root procedures",
            "Rolling or recursive unit-root analysis",
        ],
        "Classical forecasting": [
            "Mean forecast",
            "Naive forecast",
            "Seasonal naive forecast",
            "Random walk",
            "Random walk with drift",
            "Moving-average forecast",
            "Simple exponential smoothing",
            "Holt linear trend",
            "Damped Holt trend",
            "Holt-Winters additive seasonality",
            "Holt-Winters multiplicative seasonality",
            "ETS",
            "Theta",
            "Four-Theta",
            "Croston",
            "SBA intermittent-demand model",
            "TSB intermittent-demand model",
            "BATS",
            "TBATS",
            "AutoETS",
            "AutoTheta",
            "AutoTBATS",
            "Complex exponential smoothing",
            "Multiple-frequency seasonality models",
        ],
        "Autoregressive and ARIMA family": [
            "AutoReg / AR",
            "ARX",
            "ARMA",
            "ARMAX",
            "ARIMA",
            "ARIMAX",
            "SARIMA",
            "SARIMAX",
            "Regression with ARIMA errors",
            "Seasonal dynamic regression",
            "Transfer-function models",
            "Distributed-lag models",
            "ARDL",
            "UECM",
            "Error-correction models",
            "AutoARIMA",
            "ARFIMA",
            "Threshold autoregression",
            "Smooth-transition autoregression",
            "Self-exciting threshold autoregression",
            "Nonlinear autoregression",
        ],
        "State-space and structural models": [
            "Kalman filter",
            "Kalman smoother",
            "Local-level model",
            "Local-linear-trend model",
            "Stochastic trend model",
            "Structural time-series model",
            "Unobserved components",
            "Stochastic seasonal model",
            "Cyclical-component model",
            "Time-varying-parameter regression",
            "Dynamic linear model",
            "Dynamic factor model",
            "Mixed-frequency dynamic factor model",
            "Bayesian structural time series",
            "Custom maximum-likelihood state-space model",
            "State-space intervention analysis",
        ],
        "Regime switching and structural change": [
            "Markov-switching regression",
            "Markov-switching autoregression",
            "Threshold autoregression",
            "Smooth-transition regression",
            "Hidden Markov models",
            "Change-point detection",
            "Bai-Perron multiple structural breaks",
            "CUSUM and CUSUMSQ",
            "Chow structural-break test",
            "Quandt likelihood-ratio test",
            "Bayesian change-point models",
            "Online change-point detection",
        ],
        "Multivariate time series": [
            "VAR",
            "VAR with exogenous variables",
            "Bayesian VAR",
            "Structural VAR",
            "Factor-augmented VAR",
            "Global VAR",
            "Threshold VAR",
            "Markov-switching VAR",
            "Panel VAR",
            "VARMA",
            "VARMAX",
            "VARIMA",
            "VECM",
            "Structural VECM",
            "Dynamic factor model",
            "Dynamic conditional correlation",
            "Multivariate state-space models",
            "Mixed-frequency multivariate models",
            "Seemingly unrelated time-series regression",
        ],
        "Cointegration and long-run analysis": [
            "Engle-Granger",
            "Phillips-Ouliaris",
            "Johansen trace",
            "Johansen maximum eigenvalue",
            "Vector error correction",
            "ARDL bounds testing",
            "Fully modified OLS",
            "Dynamic OLS",
            "Canonical cointegrating regression",
            "Gregory-Hansen structural-break cointegration",
            "Threshold cointegration",
            "Nonlinear cointegration",
            "Rolling cointegration",
        ],
        "Causality and dynamic interpretation": [
            "Pairwise Granger causality",
            "Block exogeneity",
            "Toda-Yamamoto causality",
            "Dumitrescu-Hurlin panel causality",
            "Instantaneous causality",
            "Frequency-domain causality",
            "Nonlinear Granger causality",
            "Orthogonalized impulse responses",
            "Generalized impulse responses",
            "Structural impulse responses",
            "Forecast-error variance decomposition",
            "Historical decomposition",
            "Local-projection impulse responses",
            "Panel local projections",
        ],
        "Volatility and financial models": [
            "ARCH",
            "ARCH-in-Mean",
            "GARCH",
            "GARCH-in-Mean",
            "GJR-GARCH",
            "TARCH",
            "Threshold GARCH",
            "Power GARCH",
            "EGARCH",
            "FIGARCH",
            "FIAPARCH",
            "APARCH",
            "HARCH",
            "Component GARCH",
            "Integrated GARCH",
            "EWMA / RiskMetrics",
            "RiskMetrics 2006",
            "MIDAS Hyperbolic volatility",
            "Stochastic volatility",
            "Realized-volatility models",
            "HAR-RV",
            "GAS / score-driven volatility",
            "CCC-GARCH",
            "DCC-GARCH",
            "BEKK-GARCH",
            "Copula-GARCH",
            "Regime-switching GARCH",
        ],
        "Machine-learning forecasting": [
            "Linear lagged regression",
            "Ridge forecasting",
            "Lasso forecasting",
            "Elastic-net forecasting",
            "Random forest forecasting",
            "Extra Trees forecasting",
            "Gradient boosting forecasting",
            "Histogram gradient boosting forecasting",
            "XGBoost forecasting",
            "LightGBM forecasting",
            "CatBoost forecasting",
            "Support-vector forecasting",
            "K-nearest-neighbour forecasting",
            "Gaussian-process forecasting",
            "Quantile-regression forests",
            "Recursive forecasting",
            "Direct forecasting",
            "DirRec forecasting",
            "MIMO forecasting",
            "Stacked and weighted ensembles",
        ],
        "Deep learning and foundation models": [
            "Feedforward neural networks",
            "RNN",
            "LSTM",
            "GRU",
            "Block RNN",
            "Temporal convolutional network",
            "Transformer",
            "Temporal Fusion Transformer",
            "N-BEATS",
            "N-HiTS",
            "DeepAR",
            "WaveNet",
            "TiDE",
            "DLinear",
            "NLinear",
            "TSMixer",
            "PatchTST",
            "Informer",
            "Autoformer",
            "FEDformer",
            "Graph neural-network forecasting",
            "Chronos",
            "TimesFM",
            "TiRex",
            "Lag-Llama",
            "Moirai",
            "TimeGPT",
        ],
        "Other time-series tasks": [
            "Time-series classification",
            "Time-series regression",
            "Time-series clustering",
            "Anomaly and outlier detection",
            "Change-point detection",
            "Segmentation",
            "Motif discovery",
            "Matrix-profile analysis",
            "Dynamic time warping",
            "Shapelet analysis",
            "Singular-spectrum analysis",
            "Empirical-mode decomposition",
            "Wavelet analysis",
            "Spectral-density estimation",
            "Cross-spectrum and coherence",
            "Hierarchical forecasting",
            "Forecast reconciliation",
            "Probabilistic forecasting",
            "Quantile forecasting",
            "Conformal prediction",
            "Forecast combinations",
            "Rolling-origin backtesting",
        ],
    },
    "Regression": {
        "Classical linear regression": [
            "Simple linear regression",
            "Multiple linear regression",
            "Ordinary least squares",
            "Weighted least squares",
            "Generalized least squares",
            "Feasible GLS",
            "GLS with autoregressive errors",
            "Non-negative least squares",
            "Polynomial regression",
            "Spline regression",
            "Piecewise linear regression",
            "Segmented regression",
            "Rolling OLS",
            "Rolling WLS",
            "Recursive least squares",
            "Restricted least squares",
            "Constrained regression",
        ],
        "Regularized regression": [
            "Ridge regression",
            "Lasso",
            "Elastic net",
            "Least-angle regression",
            "Lasso-LARS",
            "Orthogonal matching pursuit",
            "Multi-task Lasso",
            "Multi-task Elastic Net",
            "Group Lasso",
            "Sparse-group Lasso",
            "Fused Lasso",
            "Adaptive Lasso",
            "Bayesian Lasso",
            "SCAD",
            "MCP regression",
            "Regularized generalized linear models",
            "Stochastic-gradient regression",
        ],
        "Robust and quantile regression": [
            "Least absolute deviations",
            "Median regression",
            "Quantile regression",
            "Multiple-quantile regression",
            "Expectile regression",
            "M-estimation",
            "Huber regression",
            "Hampel regression",
            "Tukey biweight regression",
            "Andrew-wave regression",
            "RANSAC",
            "Theil-Sen",
            "Siegel repeated median",
            "Robust spline regression",
        ],
        "Generalized linear models": [
            "Gaussian GLM",
            "Binomial GLM",
            "Logistic regression",
            "Probit regression",
            "Complementary log-log regression",
            "Poisson regression",
            "Negative-binomial regression",
            "Gamma regression",
            "Inverse-Gaussian regression",
            "Tweedie regression",
            "Quasi-Poisson regression",
            "Fractional logit",
            "Penalized GLM",
            "Bayesian GLM",
        ],
        "Discrete choice": [
            "Binary logit",
            "Binary probit",
            "Multinomial logit",
            "Ordered logit",
            "Ordered probit",
            "Conditional logit",
            "Conditional multinomial logit",
            "Nested logit",
            "Mixed logit",
            "Random-parameters logit",
            "Multinomial probit",
            "Rank-ordered logit",
            "Exploded logit",
            "Generalized ordered logit",
        ],
        "Count data": [
            "Poisson",
            "Negative binomial",
            "NB1",
            "NB2",
            "Generalized Poisson",
            "Zero-inflated Poisson",
            "Zero-inflated negative binomial",
            "Zero-inflated generalized Poisson",
            "Hurdle Poisson",
            "Hurdle negative binomial",
            "Truncated Poisson",
            "Truncated negative binomial",
            "Censored count regression",
            "Conway-Maxwell Poisson",
            "Poisson pseudo-maximum likelihood",
            "Fixed-effects Poisson",
        ],
        "Limited dependent variables": [
            "Tobit",
            "Left-censored regression",
            "Right-censored regression",
            "Interval regression",
            "Truncated regression",
            "Double-hurdle regression",
            "Heckman sample selection",
            "Endogenous switching regression",
            "Treatment-effects regression",
            "Fractional-response regression",
            "Beta regression",
            "Dirichlet regression",
            "Two-part models",
        ],
        "Nonparametric and semiparametric regression": [
            "Kernel regression",
            "Local-constant regression",
            "Local-linear regression",
            "LOESS / LOWESS",
            "Smoothing splines",
            "Regression splines",
            "Penalized splines",
            "Generalized additive models",
            "Isotonic regression",
            "Monotonic regression",
            "Gaussian-process regression",
            "Single-index models",
            "Partially linear models",
            "Varying-coefficient models",
            "Series regression",
            "Sieve regression",
        ],
        "Mixed, hierarchical and correlated data": [
            "Random-intercept regression",
            "Random-slope regression",
            "Crossed random effects",
            "Nested multilevel models",
            "Linear mixed effects",
            "Generalized linear mixed models",
            "Bayesian mixed effects",
            "Generalized estimating equations",
            "Nominal GEE",
            "Ordinal GEE",
            "Cluster-correlated GLM",
            "Growth-curve models",
            "Latent growth models",
            "Hierarchical Bayesian regression",
        ],
        "Instrumental variables and systems": [
            "Two-stage least squares",
            "Limited-information maximum likelihood",
            "k-class estimation",
            "Fuller-modified LIML",
            "IV-GMM",
            "Continuously updating GMM",
            "Control-function regression",
            "Seemingly unrelated regression",
            "Three-stage least squares",
            "System GMM",
            "Absorbing least squares",
            "High-dimensional fixed-effects IV",
            "Weak-instrument-robust inference",
        ],
        "Survival and duration": [
            "Cox proportional hazards",
            "Stratified Cox",
            "Time-varying Cox",
            "Exponential duration",
            "Weibull AFT",
            "Log-normal AFT",
            "Log-logistic AFT",
            "Generalized-gamma AFT",
            "Competing risks",
            "Fine-Gray",
            "Frailty models",
            "Recurrent-event models",
            "Discrete-time hazards",
            "Cure models",
        ],
        "Machine-learning regression": [
            "Decision-tree regression",
            "Random forest regression",
            "Extra-Trees regression",
            "AdaBoost regression",
            "Gradient-boosting regression",
            "Histogram gradient boosting",
            "XGBoost regression",
            "LightGBM regression",
            "CatBoost regression",
            "Support-vector regression",
            "Linear SVR",
            "K-nearest-neighbour regression",
            "Radius-neighbour regression",
            "Gaussian-process regression",
            "Multi-layer perceptron regression",
            "Partial least squares regression",
            "Principal-component regression",
            "Kernel ridge regression",
            "Quantile gradient boosting",
            "Bagging regression",
            "Voting regression",
            "Stacking regression",
            "Multi-output regression",
            "Multi-task regression",
        ],
    },
    "Panel data": {
        "Static linear panel estimators": [
            "Pooled OLS",
            "Entity fixed effects",
            "Time fixed effects",
            "Two-way fixed effects",
            "Multiway fixed effects",
            "Least-squares dummy variables",
            "Within estimator",
            "Random effects",
            "Between estimator",
            "First differences",
            "Fama-MacBeth",
            "Correlated random effects",
            "Mundlak specification",
            "Chamberlain correlated random effects",
            "Random coefficients",
            "High-dimensional absorbed fixed effects",
            "Interactive fixed effects",
            "Common-factor panel models",
        ],
        "Panel instrumental variables": [
            "Pooled panel 2SLS",
            "Fixed-effects 2SLS",
            "First-difference IV",
            "Random-effects IV",
            "Panel LIML",
            "Panel IV-GMM",
            "Fixed-effects GMM",
            "High-dimensional fixed-effects IV",
            "Panel control function",
            "Panel 3SLS",
            "Panel system regression",
            "Hausman-Taylor",
            "Amemiya-MaCurdy",
            "Breusch-Mizon-Schmidt",
        ],
        "Dynamic panel estimators": [
            "Lagged-dependent-variable fixed effects",
            "Anderson-Hsiao IV",
            "Arellano-Bond difference GMM",
            "Arellano-Bover GMM",
            "Blundell-Bond system GMM",
            "One-step GMM",
            "Two-step GMM",
            "Iterated GMM",
            "Bias-corrected LSDV",
            "Kiviet correction",
            "Bruno correction",
            "Dynamic common correlated effects",
            "Dynamic panel threshold models",
            "Panel VAR",
            "Dynamic panel quantile regression",
        ],
        "Nonlinear panel models": [
            "Fixed-effects logit",
            "Conditional logit",
            "Random-effects logit",
            "Fixed-effects probit",
            "Random-effects probit",
            "Correlated-random-effects probit",
            "Fixed-effects Poisson",
            "PPML with fixed effects",
            "Random-effects Poisson",
            "Fixed-effects negative binomial",
            "Random-effects negative binomial",
            "Panel multinomial logit",
            "Panel ordered logit",
            "Panel ordered probit",
            "Panel Tobit",
            "Dynamic panel logit",
            "Dynamic panel probit",
            "Panel hurdle models",
            "Panel zero-inflated models",
            "Panel survival models",
        ],
        "Panel quantile and distributional methods": [
            "Pooled panel quantile regression",
            "Fixed-effects quantile regression",
            "Penalized fixed-effects quantile regression",
            "Instrumental-variable quantile regression",
            "Dynamic panel quantile regression",
            "Panel expectile regression",
            "Distribution regression",
            "Quantile treatment-effect panels",
        ],
        "Difference-in-differences and event studies": [
            "Two-group two-period DiD",
            "Multiple-period DiD",
            "Two-way fixed-effects DiD",
            "Staggered-adoption DiD",
            "Dynamic event study",
            "Gardner DID2S",
            "Sun-Abraham",
            "Callaway-Sant'Anna",
            "Borusyak-Jaravel-Spiess",
            "de Chaisemartin-D'Haultfoeuille",
            "Local-projection DiD",
            "Triple differences",
            "Continuous-treatment DiD",
            "Synthetic DiD",
            "Matrix-completion causal panels",
            "Interactive-fixed-effects treatment models",
        ],
        "Synthetic control": [
            "Original synthetic control",
            "Augmented synthetic control",
            "Penalized synthetic control",
            "Robust synthetic control",
            "Generalized synthetic control",
            "Synthetic difference-in-differences",
            "Matrix-completion synthetic control",
            "Bayesian synthetic control",
            "Multiple-treated-unit synthetic control",
            "Synthetic-control event studies",
            "Synthetic interrupted time series",
        ],
        "Spatial panel": [
            "Spatial-lag panel",
            "Spatial-error panel",
            "Spatial Durbin panel",
            "Spatial autoregressive combined",
            "SARAR / SAC panel",
            "Spatial fixed effects",
            "Spatial random effects",
            "Dynamic spatial panel",
            "Spatial panel GMM",
            "Spatial panel maximum likelihood",
            "Spatial panel IV",
            "Spatial Durbin error",
            "Spatial regimes",
        ],
        "Panel unit roots": [
            "Levin-Lin-Chu",
            "Breitung",
            "Im-Pesaran-Shin",
            "Fisher ADF",
            "Fisher Phillips-Perron",
            "Maddala-Wu",
            "Choi inverse normal",
            "Hadri",
            "Hadri-Kurozumi",
            "CADF",
            "CIPS",
            "PANIC factor-based tests",
            "Panel LM unit-root tests",
            "Panel unit roots with structural breaks",
            "Second-generation bootstrap unit-root tests",
        ],
        "Panel cointegration": [
            "Pedroni",
            "Kao",
            "Westerlund error correction",
            "Fisher-Johansen",
            "Larsson-Lyhagen-Lothgren",
            "Panel Engle-Granger",
            "Panel Phillips-Ouliaris",
            "Panel cointegration with structural breaks",
            "Common-factor panel cointegration",
        ],
        "Long-run and heterogeneous estimators": [
            "Mean Group",
            "Pooled Mean Group",
            "Dynamic Fixed Effects",
            "Common Correlated Effects Pooled",
            "Common Correlated Effects Mean Group",
            "Dynamic CCE",
            "Augmented Mean Group",
            "Cross-sectionally augmented ARDL",
            "Panel ARDL / ECM",
            "Panel dynamic OLS",
            "Panel fully modified OLS",
            "Panel canonical cointegrating regression",
            "Quantile cointegrating regression",
        ],
        "Cross-sectional dependence and heterogeneity": [
            "Breusch-Pagan LM dependence",
            "Pesaran scaled LM",
            "Bias-corrected scaled LM",
            "Pesaran CD",
            "Friedman dependence",
            "Frees dependence",
            "Average pairwise residual correlation",
            "Pesaran-Yamagata Delta",
            "Adjusted Delta",
            "Swamy slope homogeneity",
            "Blomquist-Westerlund heterogeneity",
        ],
        "Panel causality and responses": [
            "Dumitrescu-Hurlin panel Granger causality",
            "Hurlin-Venet causality",
            "Emirmahmutoglu-Kose causality",
            "Panel VAR causality",
            "Panel local projections",
            "Panel impulse responses",
            "Panel forecast-error variance decomposition",
            "Heterogeneous panel causality",
        ],
        "Covariance and inference": [
            "Classical covariance",
            "White robust covariance",
            "Entity clustering",
            "Time clustering",
            "Two-way clustering",
            "Multiway clustering",
            "Driscoll-Kraay",
            "Panel HAC",
            "Fama-MacBeth covariance",
            "Panel-corrected standard errors",
            "Common-correlated-effects covariance",
            "Wild cluster bootstrap",
            "Cluster jackknife / CRV3",
            "Randomization inference",
        ],
        "Specification and diagnostic tests": [
            "Fixed-effects joint F-test",
            "Poolability test",
            "Breusch-Pagan random-effects LM",
            "Honda LM",
            "Hausman test",
            "Mundlak test",
            "Wooldridge serial-correlation test",
            "Baltagi-Wu LBI",
            "Panel Durbin-Watson",
            "Modified Wald groupwise heteroskedasticity",
            "Cross-sectional dependence tests",
            "Pesaran-Yamagata slope test",
            "Sargan test",
            "Hansen J",
            "Difference-in-Hansen",
            "Arellano-Bond AR(1) and AR(2)",
            "Weak-instrument diagnostics",
            "Endogeneity tests",
            "Panel normality tests",
            "Panel stability and structural-break tests",
        ],
    },
}

RUNNABLE_IN_ADVANCED_PAGE = {
    "AutoReg / AR",
    "Simple exponential smoothing",
    "Holt linear trend",
    "Holt-Winters additive seasonality",
    "Holt-Winters multiplicative seasonality",
    "Unobserved components",
    "Markov-switching regression",
    "Ridge regression",
    "Lasso",
    "Elastic net",
    "Polynomial regression",
    "Recursive least squares",
    "Two-way fixed-effects DiD",
    "Correlated random effects",
    "Mundlak specification",
    "Driscoll-Kraay",
    "Common Correlated Effects Pooled",
}

CORE_APP_METHODS = {
    "Ordinary least squares",
    "Weighted least squares",
    "Generalized least squares",
    "Quantile regression",
    "Binary logit",
    "Binary probit",
    "Poisson",
    "Negative binomial",
    "ARDL",
    "UECM",
    "ARIMA",
    "SARIMAX",
    "VAR",
    "VECM",
    "Engle-Granger",
    "Johansen trace",
    "Johansen maximum eigenvalue",
    "Pairwise Granger causality",
    "ARCH",
    "GARCH",
    "EGARCH",
    "FIGARCH",
    "APARCH",
    "HARCH",
    "Pooled OLS",
    "Entity fixed effects",
    "Random effects",
    "Between estimator",
    "First differences",
    "Fama-MacBeth",
    "Two-stage least squares",
    "Limited-information maximum likelihood",
    "IV-GMM",
    "Augmented Dickey-Fuller",
    "Dickey-Fuller GLS",
    "Phillips-Perron",
    "KPSS",
    "Zivot-Andrews",
    "CIPS",
    "Fisher ADF",
    "Fisher Phillips-Perron",
    "Westerlund error correction",
    "Pesaran CD",
    "Pesaran-Yamagata Delta",
}
